language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
sudo: required
services:
  - redis-server
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
install:
  - "pip install -r requirements.txt"
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "python manage.py migrate"
script:
  - "coverage run manage.py test"
after_success:
  - "coveralls"
