language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial
sudo: true
install:
  - "pip install -r requirements.txt"
before_script:
  - "python manage.py migrate"
script:
  - "coverage run manage.py test"
after_success:
  - "coveralls"
