language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
before_script:
  - "python manage.py migrate"
script:
  - "coverage run manage.py test"
after_success:
  - "coveralls"
