language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
  - "git clone https://github.com/Bartzi/django-multimail.git"
  - "cd django-multimail && python setup.py install && cd .."
  - "rm -rf django-multimail"
before_script:
  - "python manage.py migrate"
script:
  - "coverage run manage.py test"
after_success:
  - "coveralls"
