# Generated by Django 2.2.17 on 2020-12-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labshare', '0020_auto_20190805_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ip_address',
        ),
    ]
