# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labshare', '0010_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
