# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labshare', '0011_gpu_in_use'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': (('use_device', 'User/Group is allowed to use that device'),)},
        ),
    ]
