# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labshare', '0013_initial_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': (('use_device', 'User/Group is not allowed to use that device'),)},
        ),
    ]
