# Generated by Django 2.0.8 on 2018-08-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labshare', '0018_gpu_marked_as_failed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': (('use_device', 'User/Group is allowed to use that device'),)},
        ),
    ]
