# Generated by Django 2.2.17 on 2020-12-10 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labshare', '0020_auto_20190805_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
