# Generated by Django 2.2.17 on 2020-12-10 09:36

from django.contrib.auth.models import User
from django.db import migrations
from rest_framework.authtoken.models import Token

from labshare.models import Device


def create_users(apps, schema_editor):
    devices = Device.objects.all()
    for device in devices:
        username = device.name + "_user"
        user = User.objects.create_user(username)
        user.save()

        token = Token.objects.create(user=user)
        token.save()

        device.user = user
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('labshare', '0021_auto_20201210_1036'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
