# Generated by Django 2.2.17 on 2020-12-10 09:36
import binascii
import os

from django.db import migrations


# Copied from rest_framework/authtoken/models.py.
# This method is needed because token keys are not generated automatically in migrations.
def generate_key():
    return binascii.hexlify(os.urandom(20)).decode()


def create_users(apps, schema_editor):
    Device = apps.get_model('labshare', 'Device')
    devices = Device.objects.all()
    for device in devices:
        username = device.name + '_user'
        User = apps.get_model('auth', 'User')
        user, _ = User.objects.get_or_create(username=username)

        Token = apps.get_model('authtoken', 'Token', require_ready=False)
        Token.objects.get_or_create(user=user, key=generate_key())

        device.user = user
        device.save()


class Migration(migrations.Migration):
    dependencies = [
        ('labshare', '0021_auto_20201210_1036'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
