# Generated by Django 2.2.17 on 2021-08-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labshare', '0024_gpu_utilization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpuprocess',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='GPU',
        ),
        migrations.DeleteModel(
            name='GPUProcess',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
