# Generated by Django 2.2.17 on 2021-08-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labshare', '0025_auto_20210805_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('reserved', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='labshare.Device')),
            ],
        ),
    ]
