# Generated by Django 2.2.17 on 2021-08-11 09:39
import binascii
import os

from django.conf import settings
from django.db import migrations


def generate_key():
    return binascii.hexlify(os.urandom(20)).decode()


def create_allocation_update_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Token = apps.get_model("authtoken", "Token")

    allocation_user = User.objects.create(username=settings.ALLOCATION_UPDATE_USERNAME)
    allocation_user.save()
    token = Token.objects.create(user=allocation_user, key=generate_key())
    token.save()


def delete_allocation_update_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    allocation_user = User.objects.get(username=settings.ALLOCATION_UPDATE_USERNAME)
    allocation_user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('labshare', '0026_gpu'),
    ]

    operations = [
        migrations.RunPython(create_allocation_update_user, delete_allocation_update_user)
    ]
